/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.pickamix.server.database.codegen.enums.MeasuresDatatype;
import jhi.pickamix.server.database.codegen.tables.Measures;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeasuresRecord extends UpdatableRecordImpl<MeasuresRecord> implements Record7<Integer, String, String, String, MeasuresDatatype, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pickamix_db.measures.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pickamix_db.measures.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pickamix_db.measures.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pickamix_db.measures.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pickamix_db.measures.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pickamix_db.measures.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pickamix_db.measures.icon</code>.
     */
    public void setIcon(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pickamix_db.measures.icon</code>.
     */
    public String getIcon() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pickamix_db.measures.datatype</code>.
     */
    public void setDatatype(MeasuresDatatype value) {
        set(4, value);
    }

    /**
     * Getter for <code>pickamix_db.measures.datatype</code>.
     */
    public MeasuresDatatype getDatatype() {
        return (MeasuresDatatype) get(4);
    }

    /**
     * Setter for <code>pickamix_db.measures.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>pickamix_db.measures.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>pickamix_db.measures.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>pickamix_db.measures.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, MeasuresDatatype, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, MeasuresDatatype, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Measures.MEASURES.ID;
    }

    @Override
    public Field<String> field2() {
        return Measures.MEASURES.NAME;
    }

    @Override
    public Field<String> field3() {
        return Measures.MEASURES.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Measures.MEASURES.ICON;
    }

    @Override
    public Field<MeasuresDatatype> field5() {
        return Measures.MEASURES.DATATYPE;
    }

    @Override
    public Field<Timestamp> field6() {
        return Measures.MEASURES.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field7() {
        return Measures.MEASURES.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getIcon();
    }

    @Override
    public MeasuresDatatype component5() {
        return getDatatype();
    }

    @Override
    public Timestamp component6() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component7() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getIcon();
    }

    @Override
    public MeasuresDatatype value5() {
        return getDatatype();
    }

    @Override
    public Timestamp value6() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value7() {
        return getUpdatedOn();
    }

    @Override
    public MeasuresRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MeasuresRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public MeasuresRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public MeasuresRecord value4(String value) {
        setIcon(value);
        return this;
    }

    @Override
    public MeasuresRecord value5(MeasuresDatatype value) {
        setDatatype(value);
        return this;
    }

    @Override
    public MeasuresRecord value6(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public MeasuresRecord value7(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public MeasuresRecord values(Integer value1, String value2, String value3, String value4, MeasuresDatatype value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MeasuresRecord
     */
    public MeasuresRecord() {
        super(Measures.MEASURES);
    }

    /**
     * Create a detached, initialised MeasuresRecord
     */
    public MeasuresRecord(Integer id, String name, String description, String icon, MeasuresDatatype datatype, Timestamp createdOn, Timestamp updatedOn) {
        super(Measures.MEASURES);

        setId(id);
        setName(name);
        setDescription(description);
        setIcon(icon);
        setDatatype(datatype);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised MeasuresRecord
     */
    public MeasuresRecord(jhi.pickamix.server.database.codegen.tables.pojos.Measures value) {
        super(Measures.MEASURES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setIcon(value.getIcon());
            setDatatype(value.getDatatype());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
