/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.pickamix.server.database.codegen.tables.Trials;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrialsRecord extends UpdatableRecordImpl<TrialsRecord> implements Record17<Integer, String, String, String, String, Double, Double, String, String, String, String, String, String, String, Double, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pickamix_db.trials.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pickamix_db.trials.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pickamix_db.trials.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pickamix_db.trials.postcode</code>.
     */
    public void setPostcode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.postcode</code>.
     */
    public String getPostcode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pickamix_db.trials.contact_email</code>.
     */
    public void setContactEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.contact_email</code>.
     */
    public String getContactEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pickamix_db.trials.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>pickamix_db.trials.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>pickamix_db.trials.farm_management</code>.
     */
    public void setFarmManagement(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.farm_management</code>.
     */
    public String getFarmManagement() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pickamix_db.trials.weed_incidence</code>.
     */
    public void setWeedIncidence(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.weed_incidence</code>.
     */
    public String getWeedIncidence() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pickamix_db.trials.disease_incidence</code>.
     */
    public void setDiseaseIncidence(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.disease_incidence</code>.
     */
    public String getDiseaseIncidence() {
        return (String) get(9);
    }

    /**
     * Setter for <code>pickamix_db.trials.pest_incidence</code>.
     */
    public void setPestIncidence(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.pest_incidence</code>.
     */
    public String getPestIncidence() {
        return (String) get(10);
    }

    /**
     * Setter for <code>pickamix_db.trials.soil_health</code>.
     */
    public void setSoilHealth(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.soil_health</code>.
     */
    public String getSoilHealth() {
        return (String) get(11);
    }

    /**
     * Setter for <code>pickamix_db.trials.biodiversity</code>.
     */
    public void setBiodiversity(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.biodiversity</code>.
     */
    public String getBiodiversity() {
        return (String) get(12);
    }

    /**
     * Setter for <code>pickamix_db.trials.notes</code>.
     */
    public void setNotes(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.notes</code>.
     */
    public String getNotes() {
        return (String) get(13);
    }

    /**
     * Setter for <code>pickamix_db.trials.cpr</code>.
     */
    public void setCpr(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.cpr</code>.
     */
    public Double getCpr() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>pickamix_db.trials.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>pickamix_db.trials.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>pickamix_db.trials.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Integer, String, String, String, String, Double, Double, String, String, String, String, String, String, String, Double, Timestamp, Timestamp> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Integer, String, String, String, String, Double, Double, String, String, String, String, String, String, String, Double, Timestamp, Timestamp> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Trials.TRIALS.ID;
    }

    @Override
    public Field<String> field2() {
        return Trials.TRIALS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Trials.TRIALS.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Trials.TRIALS.POSTCODE;
    }

    @Override
    public Field<String> field5() {
        return Trials.TRIALS.CONTACT_EMAIL;
    }

    @Override
    public Field<Double> field6() {
        return Trials.TRIALS.LATITUDE;
    }

    @Override
    public Field<Double> field7() {
        return Trials.TRIALS.LONGITUDE;
    }

    @Override
    public Field<String> field8() {
        return Trials.TRIALS.FARM_MANAGEMENT;
    }

    @Override
    public Field<String> field9() {
        return Trials.TRIALS.WEED_INCIDENCE;
    }

    @Override
    public Field<String> field10() {
        return Trials.TRIALS.DISEASE_INCIDENCE;
    }

    @Override
    public Field<String> field11() {
        return Trials.TRIALS.PEST_INCIDENCE;
    }

    @Override
    public Field<String> field12() {
        return Trials.TRIALS.SOIL_HEALTH;
    }

    @Override
    public Field<String> field13() {
        return Trials.TRIALS.BIODIVERSITY;
    }

    @Override
    public Field<String> field14() {
        return Trials.TRIALS.NOTES;
    }

    @Override
    public Field<Double> field15() {
        return Trials.TRIALS.CPR;
    }

    @Override
    public Field<Timestamp> field16() {
        return Trials.TRIALS.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field17() {
        return Trials.TRIALS.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getPostcode();
    }

    @Override
    public String component5() {
        return getContactEmail();
    }

    @Override
    public Double component6() {
        return getLatitude();
    }

    @Override
    public Double component7() {
        return getLongitude();
    }

    @Override
    public String component8() {
        return getFarmManagement();
    }

    @Override
    public String component9() {
        return getWeedIncidence();
    }

    @Override
    public String component10() {
        return getDiseaseIncidence();
    }

    @Override
    public String component11() {
        return getPestIncidence();
    }

    @Override
    public String component12() {
        return getSoilHealth();
    }

    @Override
    public String component13() {
        return getBiodiversity();
    }

    @Override
    public String component14() {
        return getNotes();
    }

    @Override
    public Double component15() {
        return getCpr();
    }

    @Override
    public Timestamp component16() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component17() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getPostcode();
    }

    @Override
    public String value5() {
        return getContactEmail();
    }

    @Override
    public Double value6() {
        return getLatitude();
    }

    @Override
    public Double value7() {
        return getLongitude();
    }

    @Override
    public String value8() {
        return getFarmManagement();
    }

    @Override
    public String value9() {
        return getWeedIncidence();
    }

    @Override
    public String value10() {
        return getDiseaseIncidence();
    }

    @Override
    public String value11() {
        return getPestIncidence();
    }

    @Override
    public String value12() {
        return getSoilHealth();
    }

    @Override
    public String value13() {
        return getBiodiversity();
    }

    @Override
    public String value14() {
        return getNotes();
    }

    @Override
    public Double value15() {
        return getCpr();
    }

    @Override
    public Timestamp value16() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value17() {
        return getUpdatedOn();
    }

    @Override
    public TrialsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TrialsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TrialsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TrialsRecord value4(String value) {
        setPostcode(value);
        return this;
    }

    @Override
    public TrialsRecord value5(String value) {
        setContactEmail(value);
        return this;
    }

    @Override
    public TrialsRecord value6(Double value) {
        setLatitude(value);
        return this;
    }

    @Override
    public TrialsRecord value7(Double value) {
        setLongitude(value);
        return this;
    }

    @Override
    public TrialsRecord value8(String value) {
        setFarmManagement(value);
        return this;
    }

    @Override
    public TrialsRecord value9(String value) {
        setWeedIncidence(value);
        return this;
    }

    @Override
    public TrialsRecord value10(String value) {
        setDiseaseIncidence(value);
        return this;
    }

    @Override
    public TrialsRecord value11(String value) {
        setPestIncidence(value);
        return this;
    }

    @Override
    public TrialsRecord value12(String value) {
        setSoilHealth(value);
        return this;
    }

    @Override
    public TrialsRecord value13(String value) {
        setBiodiversity(value);
        return this;
    }

    @Override
    public TrialsRecord value14(String value) {
        setNotes(value);
        return this;
    }

    @Override
    public TrialsRecord value15(Double value) {
        setCpr(value);
        return this;
    }

    @Override
    public TrialsRecord value16(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public TrialsRecord value17(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public TrialsRecord values(Integer value1, String value2, String value3, String value4, String value5, Double value6, Double value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, Double value15, Timestamp value16, Timestamp value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrialsRecord
     */
    public TrialsRecord() {
        super(Trials.TRIALS);
    }

    /**
     * Create a detached, initialised TrialsRecord
     */
    public TrialsRecord(Integer id, String name, String description, String postcode, String contactEmail, Double latitude, Double longitude, String farmManagement, String weedIncidence, String diseaseIncidence, String pestIncidence, String soilHealth, String biodiversity, String notes, Double cpr, Timestamp createdOn, Timestamp updatedOn) {
        super(Trials.TRIALS);

        setId(id);
        setName(name);
        setDescription(description);
        setPostcode(postcode);
        setContactEmail(contactEmail);
        setLatitude(latitude);
        setLongitude(longitude);
        setFarmManagement(farmManagement);
        setWeedIncidence(weedIncidence);
        setDiseaseIncidence(diseaseIncidence);
        setPestIncidence(pestIncidence);
        setSoilHealth(soilHealth);
        setBiodiversity(biodiversity);
        setNotes(notes);
        setCpr(cpr);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised TrialsRecord
     */
    public TrialsRecord(jhi.pickamix.server.database.codegen.tables.pojos.Trials value) {
        super(Trials.TRIALS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setPostcode(value.getPostcode());
            setContactEmail(value.getContactEmail());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setFarmManagement(value.getFarmManagement());
            setWeedIncidence(value.getWeedIncidence());
            setDiseaseIncidence(value.getDiseaseIncidence());
            setPestIncidence(value.getPestIncidence());
            setSoilHealth(value.getSoilHealth());
            setBiodiversity(value.getBiodiversity());
            setNotes(value.getNotes());
            setCpr(value.getCpr());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
