/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables.records;


import java.sql.Timestamp;

import jhi.pickamix.server.database.codegen.tables.ViewTrials;
import jhi.pickamix.server.database.codegen.tables.pojos.Components;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTrialsRecord extends TableRecordImpl<ViewTrialsRecord> implements Record13<Integer, String, String, Double, Double, Timestamp, String, String, String, String, String, String, Components[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pickamix_db.view_trials.trial_id</code>.
     */
    public void setTrialId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_id</code>.
     */
    public Integer getTrialId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_name</code>.
     */
    public void setTrialName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_name</code>.
     */
    public String getTrialName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_description</code>.
     */
    public void setTrialDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_description</code>.
     */
    public String getTrialDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_latitude</code>.
     */
    public void setTrialLatitude(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_latitude</code>.
     */
    public Double getTrialLatitude() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_longitude</code>.
     */
    public void setTrialLongitude(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_longitude</code>.
     */
    public Double getTrialLongitude() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_created_on</code>.
     */
    public void setTrialCreatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_created_on</code>.
     */
    public Timestamp getTrialCreatedOn() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_farm_management</code>.
     */
    public void setTrialFarmManagement(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_farm_management</code>.
     */
    public String getTrialFarmManagement() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_weed_incidence</code>.
     */
    public void setTrialWeedIncidence(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_weed_incidence</code>.
     */
    public String getTrialWeedIncidence() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_disease_incidence</code>.
     */
    public void setTrialDiseaseIncidence(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_disease_incidence</code>.
     */
    public String getTrialDiseaseIncidence() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_pest_incidence</code>.
     */
    public void setTrialPestIncidence(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_pest_incidence</code>.
     */
    public String getTrialPestIncidence() {
        return (String) get(9);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_soil_health</code>.
     */
    public void setTrialSoilHealth(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_soil_health</code>.
     */
    public String getTrialSoilHealth() {
        return (String) get(10);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_biodiversity</code>.
     */
    public void setTrialBiodiversity(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_biodiversity</code>.
     */
    public String getTrialBiodiversity() {
        return (String) get(11);
    }

    /**
     * Setter for <code>pickamix_db.view_trials.trial_components</code>.
     */
    public void setTrialComponents(Components[] value) {
        set(12, value);
    }

    /**
     * Getter for <code>pickamix_db.view_trials.trial_components</code>.
     */
    public Components[] getTrialComponents() {
        return (Components[]) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, String, Double, Double, Timestamp, String, String, String, String, String, String, Components[]> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, String, String, Double, Double, Timestamp, String, String, String, String, String, String, Components[]> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewTrials.VIEW_TRIALS.TRIAL_ID;
    }

    @Override
    public Field<String> field2() {
        return ViewTrials.VIEW_TRIALS.TRIAL_NAME;
    }

    @Override
    public Field<String> field3() {
        return ViewTrials.VIEW_TRIALS.TRIAL_DESCRIPTION;
    }

    @Override
    public Field<Double> field4() {
        return ViewTrials.VIEW_TRIALS.TRIAL_LATITUDE;
    }

    @Override
    public Field<Double> field5() {
        return ViewTrials.VIEW_TRIALS.TRIAL_LONGITUDE;
    }

    @Override
    public Field<Timestamp> field6() {
        return ViewTrials.VIEW_TRIALS.TRIAL_CREATED_ON;
    }

    @Override
    public Field<String> field7() {
        return ViewTrials.VIEW_TRIALS.TRIAL_FARM_MANAGEMENT;
    }

    @Override
    public Field<String> field8() {
        return ViewTrials.VIEW_TRIALS.TRIAL_WEED_INCIDENCE;
    }

    @Override
    public Field<String> field9() {
        return ViewTrials.VIEW_TRIALS.TRIAL_DISEASE_INCIDENCE;
    }

    @Override
    public Field<String> field10() {
        return ViewTrials.VIEW_TRIALS.TRIAL_PEST_INCIDENCE;
    }

    @Override
    public Field<String> field11() {
        return ViewTrials.VIEW_TRIALS.TRIAL_SOIL_HEALTH;
    }

    @Override
    public Field<String> field12() {
        return ViewTrials.VIEW_TRIALS.TRIAL_BIODIVERSITY;
    }

    @Override
    public Field<Components[]> field13() {
        return ViewTrials.VIEW_TRIALS.TRIAL_COMPONENTS;
    }

    @Override
    public Integer component1() {
        return getTrialId();
    }

    @Override
    public String component2() {
        return getTrialName();
    }

    @Override
    public String component3() {
        return getTrialDescription();
    }

    @Override
    public Double component4() {
        return getTrialLatitude();
    }

    @Override
    public Double component5() {
        return getTrialLongitude();
    }

    @Override
    public Timestamp component6() {
        return getTrialCreatedOn();
    }

    @Override
    public String component7() {
        return getTrialFarmManagement();
    }

    @Override
    public String component8() {
        return getTrialWeedIncidence();
    }

    @Override
    public String component9() {
        return getTrialDiseaseIncidence();
    }

    @Override
    public String component10() {
        return getTrialPestIncidence();
    }

    @Override
    public String component11() {
        return getTrialSoilHealth();
    }

    @Override
    public String component12() {
        return getTrialBiodiversity();
    }

    @Override
    public Components[] component13() {
        return getTrialComponents();
    }

    @Override
    public Integer value1() {
        return getTrialId();
    }

    @Override
    public String value2() {
        return getTrialName();
    }

    @Override
    public String value3() {
        return getTrialDescription();
    }

    @Override
    public Double value4() {
        return getTrialLatitude();
    }

    @Override
    public Double value5() {
        return getTrialLongitude();
    }

    @Override
    public Timestamp value6() {
        return getTrialCreatedOn();
    }

    @Override
    public String value7() {
        return getTrialFarmManagement();
    }

    @Override
    public String value8() {
        return getTrialWeedIncidence();
    }

    @Override
    public String value9() {
        return getTrialDiseaseIncidence();
    }

    @Override
    public String value10() {
        return getTrialPestIncidence();
    }

    @Override
    public String value11() {
        return getTrialSoilHealth();
    }

    @Override
    public String value12() {
        return getTrialBiodiversity();
    }

    @Override
    public Components[] value13() {
        return getTrialComponents();
    }

    @Override
    public ViewTrialsRecord value1(Integer value) {
        setTrialId(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value2(String value) {
        setTrialName(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value3(String value) {
        setTrialDescription(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value4(Double value) {
        setTrialLatitude(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value5(Double value) {
        setTrialLongitude(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value6(Timestamp value) {
        setTrialCreatedOn(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value7(String value) {
        setTrialFarmManagement(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value8(String value) {
        setTrialWeedIncidence(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value9(String value) {
        setTrialDiseaseIncidence(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value10(String value) {
        setTrialPestIncidence(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value11(String value) {
        setTrialSoilHealth(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value12(String value) {
        setTrialBiodiversity(value);
        return this;
    }

    @Override
    public ViewTrialsRecord value13(Components[] value) {
        setTrialComponents(value);
        return this;
    }

    @Override
    public ViewTrialsRecord values(Integer value1, String value2, String value3, Double value4, Double value5, Timestamp value6, String value7, String value8, String value9, String value10, String value11, String value12, Components[] value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewTrialsRecord
     */
    public ViewTrialsRecord() {
        super(ViewTrials.VIEW_TRIALS);
    }

    /**
     * Create a detached, initialised ViewTrialsRecord
     */
    public ViewTrialsRecord(Integer trialId, String trialName, String trialDescription, Double trialLatitude, Double trialLongitude, Timestamp trialCreatedOn, String trialFarmManagement, String trialWeedIncidence, String trialDiseaseIncidence, String trialPestIncidence, String trialSoilHealth, String trialBiodiversity, Components[] trialComponents) {
        super(ViewTrials.VIEW_TRIALS);

        setTrialId(trialId);
        setTrialName(trialName);
        setTrialDescription(trialDescription);
        setTrialLatitude(trialLatitude);
        setTrialLongitude(trialLongitude);
        setTrialCreatedOn(trialCreatedOn);
        setTrialFarmManagement(trialFarmManagement);
        setTrialWeedIncidence(trialWeedIncidence);
        setTrialDiseaseIncidence(trialDiseaseIncidence);
        setTrialPestIncidence(trialPestIncidence);
        setTrialSoilHealth(trialSoilHealth);
        setTrialBiodiversity(trialBiodiversity);
        setTrialComponents(trialComponents);
    }

    /**
     * Create a detached, initialised ViewTrialsRecord
     */
    public ViewTrialsRecord(jhi.pickamix.server.database.codegen.tables.pojos.ViewTrials value) {
        super(ViewTrials.VIEW_TRIALS);

        if (value != null) {
            setTrialId(value.getTrialId());
            setTrialName(value.getTrialName());
            setTrialDescription(value.getTrialDescription());
            setTrialLatitude(value.getTrialLatitude());
            setTrialLongitude(value.getTrialLongitude());
            setTrialCreatedOn(value.getTrialCreatedOn());
            setTrialFarmManagement(value.getTrialFarmManagement());
            setTrialWeedIncidence(value.getTrialWeedIncidence());
            setTrialDiseaseIncidence(value.getTrialDiseaseIncidence());
            setTrialPestIncidence(value.getTrialPestIncidence());
            setTrialSoilHealth(value.getTrialSoilHealth());
            setTrialBiodiversity(value.getTrialBiodiversity());
            setTrialComponents(value.getTrialComponents());
        }
    }
    // @formatter:on
}
