/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import jhi.pickamix.server.database.codegen.enums.MeasuresDatatype;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Measures implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer          id;
    private String           name;
    private String           description;
    private String           icon;
    private MeasuresDatatype datatype;
    private Timestamp        createdOn;
    private Timestamp        updatedOn;

    public Measures() {}

    public Measures(Measures value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.icon = value.icon;
        this.datatype = value.datatype;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Measures(
        Integer          id,
        String           name,
        String           description,
        String           icon,
        MeasuresDatatype datatype,
        Timestamp        createdOn,
        Timestamp        updatedOn
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.icon = icon;
        this.datatype = datatype;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Measures (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(icon);
        sb.append(", ").append(datatype);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
