/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables.pojos;


import java.io.Serializable;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlotComponents implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer plotId;
    private Integer componentId;

    public PlotComponents() {}

    public PlotComponents(PlotComponents value) {
        this.plotId = value.plotId;
        this.componentId = value.componentId;
    }

    public PlotComponents(
        Integer plotId,
        Integer componentId
    ) {
        this.plotId = plotId;
        this.componentId = componentId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlotComponents (");

        sb.append(plotId);
        sb.append(", ").append(componentId);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
