/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrialMeasures implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private Integer   trialId;
    private Integer   measureId;
    private String    value;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public TrialMeasures() {}

    public TrialMeasures(TrialMeasures value) {
        this.id = value.id;
        this.trialId = value.trialId;
        this.measureId = value.measureId;
        this.value = value.value;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public TrialMeasures(
        Integer   id,
        Integer   trialId,
        Integer   measureId,
        String    value,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.trialId = trialId;
        this.measureId = measureId;
        this.value = value;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TrialMeasures (");

        sb.append(id);
        sb.append(", ").append(trialId);
        sb.append(", ").append(measureId);
        sb.append(", ").append(value);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
