/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trials implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    name;
    private String    description;
    private String    postcode;
    private String    contactEmail;
    private Double    latitude;
    private Double    longitude;
    private String    farmManagement;
    private String    weedIncidence;
    private String    diseaseIncidence;
    private String    pestIncidence;
    private String    soilHealth;
    private String    biodiversity;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Trials() {}

    public Trials(Trials value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.postcode = value.postcode;
        this.contactEmail = value.contactEmail;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.farmManagement = value.farmManagement;
        this.weedIncidence = value.weedIncidence;
        this.diseaseIncidence = value.diseaseIncidence;
        this.pestIncidence = value.pestIncidence;
        this.soilHealth = value.soilHealth;
        this.biodiversity = value.biodiversity;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Trials(
        Integer   id,
        String    name,
        String    description,
        String    postcode,
        String    contactEmail,
        Double    latitude,
        Double    longitude,
        String    farmManagement,
        String    weedIncidence,
        String    diseaseIncidence,
        String    pestIncidence,
        String    soilHealth,
        String    biodiversity,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.postcode = postcode;
        this.contactEmail = contactEmail;
        this.latitude = latitude;
        this.longitude = longitude;
        this.farmManagement = farmManagement;
        this.weedIncidence = weedIncidence;
        this.diseaseIncidence = diseaseIncidence;
        this.pestIncidence = pestIncidence;
        this.soilHealth = soilHealth;
        this.biodiversity = biodiversity;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Trials (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(postcode);
        sb.append(", ").append(contactEmail);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(farmManagement);
        sb.append(", ").append(weedIncidence);
        sb.append(", ").append(diseaseIncidence);
        sb.append(", ").append(pestIncidence);
        sb.append(", ").append(soilHealth);
        sb.append(", ").append(biodiversity);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
