/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables.pojos;


import java.io.Serializable;

import jhi.pickamix.server.database.codegen.enums.ViewTrialComponentMeasuresMeasureDatatype;
import jhi.pickamix.server.database.codegen.enums.ViewTrialComponentMeasuresPlotMeasurementType;


import lombok.*;
import lombok.experimental.Accessors;

// @formatter:off
/**
 * VIEW
 */
@Getter
@Setter
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewTrialComponentMeasures implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer                                       componentId;
    private String                                        componentCrop;
    private String                                        componentVariety;
    private Integer                                       measureId;
    private String                                        measureName;
    private ViewTrialComponentMeasuresMeasureDatatype     measureDatatype;
    private ViewTrialComponentMeasuresPlotMeasurementType plotMeasurementType;
    private String                                        measureValue;
    private Integer                                       trialId;
    private String                                        trialName;

    public ViewTrialComponentMeasures() {}

    public ViewTrialComponentMeasures(ViewTrialComponentMeasures value) {
        this.componentId = value.componentId;
        this.componentCrop = value.componentCrop;
        this.componentVariety = value.componentVariety;
        this.measureId = value.measureId;
        this.measureName = value.measureName;
        this.measureDatatype = value.measureDatatype;
        this.plotMeasurementType = value.plotMeasurementType;
        this.measureValue = value.measureValue;
        this.trialId = value.trialId;
        this.trialName = value.trialName;
    }

    public ViewTrialComponentMeasures(
        Integer                                       componentId,
        String                                        componentCrop,
        String                                        componentVariety,
        Integer                                       measureId,
        String                                        measureName,
        ViewTrialComponentMeasuresMeasureDatatype     measureDatatype,
        ViewTrialComponentMeasuresPlotMeasurementType plotMeasurementType,
        String                                        measureValue,
        Integer                                       trialId,
        String                                        trialName
    ) {
        this.componentId = componentId;
        this.componentCrop = componentCrop;
        this.componentVariety = componentVariety;
        this.measureId = measureId;
        this.measureName = measureName;
        this.measureDatatype = measureDatatype;
        this.plotMeasurementType = plotMeasurementType;
        this.measureValue = measureValue;
        this.trialId = trialId;
        this.trialName = trialName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewTrialComponentMeasures (");

        sb.append(componentId);
        sb.append(", ").append(componentCrop);
        sb.append(", ").append(componentVariety);
        sb.append(", ").append(measureId);
        sb.append(", ").append(measureName);
        sb.append(", ").append(measureDatatype);
        sb.append(", ").append(plotMeasurementType);
        sb.append(", ").append(measureValue);
        sb.append(", ").append(trialId);
        sb.append(", ").append(trialName);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
