/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables;


import java.sql.Timestamp;

import jhi.pickamix.server.database.codegen.PickamixDb;
import jhi.pickamix.server.database.codegen.tables.records.PlotMeasuresRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlotMeasures extends TableImpl<PlotMeasuresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pickamix_db.plot_measures</code>
     */
    public static final PlotMeasures PLOT_MEASURES = new PlotMeasures();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlotMeasuresRecord> getRecordType() {
        return PlotMeasuresRecord.class;
    }

    /**
     * The column <code>pickamix_db.plot_measures.id</code>.
     */
    public final TableField<PlotMeasuresRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>pickamix_db.plot_measures.plot_id</code>.
     */
    public final TableField<PlotMeasuresRecord, Integer> PLOT_ID = createField(DSL.name("plot_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>pickamix_db.plot_measures.measure_id</code>.
     */
    public final TableField<PlotMeasuresRecord, Integer> MEASURE_ID = createField(DSL.name("measure_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>pickamix_db.plot_measures.value</code>.
     */
    public final TableField<PlotMeasuresRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>pickamix_db.plot_measures.created_on</code>.
     */
    public final TableField<PlotMeasuresRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>pickamix_db.plot_measures.updated_on</code>.
     */
    public final TableField<PlotMeasuresRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    private PlotMeasures(Name alias, Table<PlotMeasuresRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlotMeasures(Name alias, Table<PlotMeasuresRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pickamix_db.plot_measures</code> table reference
     */
    public PlotMeasures(String alias) {
        this(DSL.name(alias), PLOT_MEASURES);
    }

    /**
     * Create an aliased <code>pickamix_db.plot_measures</code> table reference
     */
    public PlotMeasures(Name alias) {
        this(alias, PLOT_MEASURES);
    }

    /**
     * Create a <code>pickamix_db.plot_measures</code> table reference
     */
    public PlotMeasures() {
        this(DSL.name("plot_measures"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PickamixDb.PICKAMIX_DB;
    }

    @Override
    public Identity<PlotMeasuresRecord, Integer> getIdentity() {
        return (Identity<PlotMeasuresRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlotMeasuresRecord> getPrimaryKey() {
        return Internal.createUniqueKey(PlotMeasures.PLOT_MEASURES, DSL.name("KEY_plot_measures_PRIMARY"), new TableField[] { PlotMeasures.PLOT_MEASURES.ID }, true);
    }

    @Override
    public PlotMeasures as(String alias) {
        return new PlotMeasures(DSL.name(alias), this);
    }

    @Override
    public PlotMeasures as(Name alias) {
        return new PlotMeasures(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlotMeasures rename(String name) {
        return new PlotMeasures(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlotMeasures rename(Name name) {
        return new PlotMeasures(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
    // @formatter:on
}
