/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.tables;


import java.sql.Timestamp;

import jhi.pickamix.server.database.codegen.PickamixDb;
import jhi.pickamix.server.database.codegen.enums.PlotsMeasurementType;
import jhi.pickamix.server.database.codegen.tables.records.PlotsRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plots extends TableImpl<PlotsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pickamix_db.plots</code>
     */
    public static final Plots PLOTS = new Plots();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlotsRecord> getRecordType() {
        return PlotsRecord.class;
    }

    /**
     * The column <code>pickamix_db.plots.id</code>.
     */
    public final TableField<PlotsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>pickamix_db.plots.trial_id</code>.
     */
    public final TableField<PlotsRecord, Integer> TRIAL_ID = createField(DSL.name("trial_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>pickamix_db.plots.measurement_type</code>.
     */
    public final TableField<PlotsRecord, PlotsMeasurementType> MEASUREMENT_TYPE = createField(DSL.name("measurement_type"), SQLDataType.VARCHAR(4).nullable(false).defaultValue(DSL.inline("mono", SQLDataType.VARCHAR)).asEnumDataType(jhi.pickamix.server.database.codegen.enums.PlotsMeasurementType.class), this, "");

    /**
     * The column <code>pickamix_db.plots.created_on</code>.
     */
    public final TableField<PlotsRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>pickamix_db.plots.updated_on</code>.
     */
    public final TableField<PlotsRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    private Plots(Name alias, Table<PlotsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Plots(Name alias, Table<PlotsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pickamix_db.plots</code> table reference
     */
    public Plots(String alias) {
        this(DSL.name(alias), PLOTS);
    }

    /**
     * Create an aliased <code>pickamix_db.plots</code> table reference
     */
    public Plots(Name alias) {
        this(alias, PLOTS);
    }

    /**
     * Create a <code>pickamix_db.plots</code> table reference
     */
    public Plots() {
        this(DSL.name("plots"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PickamixDb.PICKAMIX_DB;
    }

    @Override
    public Identity<PlotsRecord, Integer> getIdentity() {
        return (Identity<PlotsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlotsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Plots.PLOTS, DSL.name("KEY_plots_PRIMARY"), new TableField[] { Plots.PLOTS.ID }, true);
    }

    @Override
    public Plots as(String alias) {
        return new Plots(DSL.name(alias), this);
    }

    @Override
    public Plots as(Name alias) {
        return new Plots(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Plots rename(String name) {
        return new Plots(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Plots rename(Name name) {
        return new Plots(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, PlotsMeasurementType, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
    // @formatter:on
}
