/*
 * This file is generated by jOOQ.
 */
package jhi.pickamix.server.database.codegen.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PlotsMeasurementType implements EnumType {

    mix("mix"),

    mono("mono");

    private final String literal;

    private PlotsMeasurementType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "plots_measurement_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static PlotsMeasurementType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(PlotsMeasurementType.class, literal);
    }
    // @formatter:on
}
